# Generated by Django 4.0.5 on 2022-07-06 22:33

from django.db import migrations, models
import django.db.models.deletion
import visualization.memvalidators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_or_privates', models.CharField(max_length=20)),
                ('categories', models.CharField(max_length=20)),
                ('agency', models.TextField()),
                ('agency_email', models.EmailField(max_length=200, null=True, validators=[visualization.memvalidators.agency_validemail])),
                ('agency_password', models.CharField(max_length=500, null=True, validators=[visualization.memvalidators.agency_validpw])),
                ('address', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('phone_numbers', models.CharField(blank=True, max_length=30, null=True)),
                ('introductions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyMembers',
            fields=[
                ('myemail', models.EmailField(max_length=200, validators=[visualization.memvalidators.validemail])),
                ('mypassword', models.CharField(max_length=500, validators=[visualization.memvalidators.validpw])),
                ('mynickname', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.TextField()),
                ('board_content', models.TextField()),
                ('members_mynickname', models.ForeignKey(db_column='mymembers_mynickname', on_delete=django.db.models.deletion.CASCADE, related_name='mymembers', to='visualization.mymembers')),
                ('mental_address', models.ForeignKey(db_column='mentalservicelocation_address', on_delete=django.db.models.deletion.CASCADE, related_name='mentalservicelocation', to='visualization.mentalservicelocation')),
            ],
        ),
        migrations.CreateModel(
            name='MentalBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.myboard')),
                ('mental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.mentalservicelocation')),
            ],
            options={
                'db_table': 'mental_board',
            },
        ),
        migrations.CreateModel(
            name='MemberBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.myboard')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.mymembers')),
            ],
            options={
                'db_table': 'member_board',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visualization.myboard')),
            ],
        ),
    ]
